Header header

float32 action_steer
float32 action_throttle
float32 action_brake

float32 error_lateral
float32 error_yaw
float32 error_speed

float64 actual_xt
float64 actual_yt
float32 actual_yaw_t
float64 actual_xh
float64 actual_yh
float32 actual_yaw_h
float64 actual_speed

float64 target_x
float64 target_y
float64 target_brake

float32[] pmap
float32[] potential_x
float32[] potential_y

float32 deg_ref_yaw
float32 deg_actual_yaw
float32 deg_error_yaw
