Header header

float32 action_steer
float32 action_throttle
float32 action_brake

float32 error_lateral
float32 error_yaw
float32 error_speed

float64 actual_xt
float64 actual_yt
float32 actual_yaw_t
float64 actual_xh
float64 actual_yh
float32 actual_yaw_h
float64 actual_speed

uint32 wp_idx
float64 ref_xt
float64 ref_yt
float32 ref_yaw_t
float64 ref_xh
float64 ref_yh
float32 ref_yaw_h

float32 ref_speed
float32 ref_curvature

float32 deg_ref_yaw_t
float32 deg_actual_yaw_t
float32 deg_error_yaw_t
float32 deg_ref_yaw_h
float32 deg_actual_yaw_h
float32 deg_error_yaw_h